name: 💀 Bug Report / Сообщить о баге
description: Found a bug in RimTUB? Describe it here / Нашли баг? Опишите его здесь
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **If you don't know something — just put `-` and explain in the comments.**  
        **Если вы чего-то не знаете — поставьте прочерк `-` и напишите в комментарии.**

        🆔 _How to get versions / Как узнать версии:_
        - RimTUB: в Telegram отправьте `.me` в любой чат / on Telegram send `.me` to any chat
        - Python: откройте терминал и напишите `python -V` / open a Terminal and type `python -V`
        
        💭 _Где взять логи? / Where I can get logs?:_
        просто приложи файл `logs/last_run.log` / just attach `logs/last_run.log` file

  - type: input
    id: rimtub
    attributes:
      label: RimTUB version / Версия RimTUB
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version / Версия Python
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform / Платформа
      placeholder: "e.g. Windows 10, Linux (Debian 11), Termux"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce / Как воспроизвести
      placeholder: |
        1. Launch RimTUB / Запустить RimTUB
        2. Ввести .example 123 / type .example 123
        3. Бот крашится / The bot crashes
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior / Как должно быть
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Логи
      description: Attach logs (preferably `logs/last_run.log`) / Приложите `logs/last_run.log`
    validations:
      required: false

  - type: textarea
    id: comment
    attributes:
      label: Additional info / Дополнительная информация
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Telegram contact (optional) / Контакт в Telegram (необязательно)
      placeholder: "@yourusername"
    validations:
      required: false
