name: 🌐 Translation issue / Ошибка в переводе
description: Report a wrong translation / Сообщите о неточности в переводе
labels: [translation]
body:
  - type: input
    id: rimtub_version
    attributes:
      label: RimTUB version / Версия RimTUB
    validations:
      required: true

  - type: input
    id: module_version
    attributes:
      label: Module version (if any) / Версия модуля
    validations:
      required: false

  - type: input
    id: lang
    attributes:
      label: Language / Язык
    validations:
      required: true

  - type: textarea
    id: correct
    attributes:
      label: Correct version / Как должно быть
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: Comment / Дополнение
