name: 🌐 Translation Error / Ошибка в переводе
description: Report a translation problem / Сообщите об ошибке в переводе
title: "[TRANSLATION] "
labels: [translation]
body:
  - type: markdown
    attributes:
      value: |
        **If you don't know something — just put `-` and explain in the comments.**  
        **Если вы чего-то не знаете — поставьте прочерк `-` и напишите в комментарии.**

        🆔 _How to get versions / Как узнать версии:_
        - RimTUB: в Telegram отправьте `.me` в любой чат / on Telegram send `.me` to any chat
        - Python: откройте терминал и напишите `python -V` / open a Terminal and type `python -V`
        
        💭 _Где взять логи? / Where I can get logs?:_
        просто приложи файл `logs/last_run.log` / just attach `logs/last_run.log` file


  - type: input
    id: rimtub
    attributes:
      label: RimTUB version / Версия RimTUB
    validations:
      required: true

  - type: input
    id: module
    attributes:
      label: Module version (if any) / Версия модуля (если есть)
    validations:
      required: false

  - type: input
    id: lang
    attributes:
      label: Language / Язык
      placeholder: "e.g. Russian, Ukrainian or Italian"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What's wrong? / Что не так?
    validations:
      required: true

  - type: textarea
    id: correct
    attributes:
      label: Correct version / Как должно быть
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: Additional info / Дополнительно
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Telegram contact (optional) / Контакт в Telegram (необязательно)
      placeholder: "@yourusername"
    validations:
      required: false
